name = "rss-to-email"
main = "src/index.js"
compatibility_date = "2024-01-01"
triggers = { crons = ["0 8 * * *"] } # Run once a day at 8:00 AM UTC

[vars]
ENVIRONMENT = "production"
# Email configuration
EMAIL_TO = "your-email@example.com"
EMAIL_FROM = "rss-updates@your-domain.com"
EMAIL_SUBJECT = "Daily Blog Updates"

[observability]
enabled = true

[[kv_namespaces]]
binding = "RSS_FEEDS"
id = "54b3bc8f456742e5858275e035f54b14"