name = "rss-to-email"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
triggers = { crons = ["0 8 * * *"] } # Run once a day at 8:00 AM UTC

[vars]
EMAIL_ADDRESS = "lillispm@gmail.com"

[observability]
enabled = true

[[kv_namespaces]]
binding = "RSS_TO_EMAIL"
id = "5c983f4a1baf4aa6b1ebe0319b1d61e2"
